name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: 'stable'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - run: goimports -w .
      - run: go mod tidy
      # If there are any diffs from goimports or go mod tidy, fail.
      - name: Verify no changes from goimports and go mod tidy
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status --porcelain
            exit 1
          fi
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: 'stable'
      - run: go test ./...
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tika-version: ['1.19', '1.20', '1.21', '2.6.0', '2.7.0', '2.8.0', '2.9.4', '3.0.0', '3.1.0', '3.2.3', '3.3.2', '4.1.0']
    env:
      TIKA_VERSION: ${{ matrix.tika-version }}
      TIKA_JAR_DIR: ${{ github.workspace }}/.tika
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: 'stable'
      - uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4.9.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mkdir -p "$TIKA_JAR_DIR"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .tika
          key: tika-server-${{ matrix.tika-version }}
      - run: go test -tags integration -run Integration -v ./tika/
